version: '2'
services:
    parisbynight-app:
        image: parisbynight
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:postgresql://parisbynight-postgresql:5432/ParisByNight
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    parisbynight-postgresql:
        extends:
            file: postgresql.yml
            service: parisbynight-postgresql
